---
title: "README"
author: '@Yujie Ma'
date: "2021/5/23"
output: html_document
---

#project structure

-- data
This directory is used to store data file, which contains a csv file named AgeAdvantagesEmotionCovid_Data. 

-- docs
This directory is used to store document files, including an Rmd file called heat_map_for_visualization_emotions_correlation_in_COVID-19_pandemic and a txt file named codebook for describing data values and definitions included.

-- image
This directory is used to store images generated by running code.

-- renv
This path is used to store the packages that the project depends on, which is for an automated system for package management. 

-- heat_map_for_visualization_emotions_correlation_in_COVID-19_pandemic.R
This the project code for plotting graphs run in the Rmd file.

# note

I tried to use renv in my Rmd file, but when I tried to Knit it, I found that I needed to set a mirror for installing all of the packages in the Rmd file, which conflicted with the automated system package management. But I can use it smoothly in my .R file, so I only submit my .R file using an automated system for package management. I am not sure if it is my skills limitation, but always happy to hear any suggestions from anyone who can make it. Thank you very much!
